/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint returning basic API information.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity
         * @description Get agent activity feed from audit_log.
         *
         *     F003-P1-001 + F003-CL-003 Remediation: Wires activity endpoint to real audit_log data.
         *
         *     RT-ACT-1 Specs:
         *     - Pagination: limit/offset with default limit=50
         *     - Ordering: newest-first (created_at DESC, id DESC)
         *     - Redaction: Only safe fields returned (no raw payloads/tokens)
         *     - Correlation: Each event has at least one correlation key
         *
         *     Args:
         *         request: The FastAPI request object
         *         limit: Max events to return (default 50, max 100)
         *         offset: Number of events to skip
         *
