# generated by datamodel-codegen:
#   filename:  zakops-api.json
#   timestamp: 2026-02-06T20:33:15+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Dict, List, Optional, Union
from uuid import UUID

from pydantic import BaseModel, EmailStr, Field, RootModel


class ActionApprove(BaseModel):
    approved_by: Annotated[Optional[str], Field(title="Approved By")] = "ui_user"
    notes: Annotated[Optional[str], Field(title="Notes")] = None


class ActionReject(BaseModel):
    reason: Annotated[str, Field(title="Reason")]
    rejected_by: Annotated[Optional[str], Field(title="Rejected By")] = "ui_user"


class ActionResponse(BaseModel):
    action_id: Annotated[str, Field(title="Action Id")]
    action_type: Annotated[str, Field(title="Action Type")]
    capability_id: Annotated[str, Field(title="Capability Id")]
    created_at: Annotated[datetime, Field(title="Created At")]
    deal_id: Annotated[Optional[str], Field(title="Deal Id")] = None
    deal_name: Annotated[Optional[str], Field(title="Deal Name")] = None
    deal_stage: Annotated[Optional[str], Field(title="Deal Stage")] = None
    inputs: Annotated[Dict[str, Any], Field(title="Inputs")]
    outputs: Annotated[Dict[str, Any], Field(title="Outputs")]
    requires_human_review: Annotated[bool, Field(title="Requires Human Review")]
    risk_level: Annotated[str, Field(title="Risk Level")]
    status: Annotated[str, Field(title="Status")]
    summary: Annotated[Optional[str], Field(title="Summary")] = None
    title: Annotated[str, Field(title="Title")]
    updated_at: Annotated[datetime, Field(title="Updated At")]


class ActionSearchResult(BaseModel):
    action_id: Annotated[str, Field(title="Action Id")]
    action_type: Annotated[str, Field(title="Action Type")]
    created_at: Annotated[str, Field(title="Created At")]
    deal_id: Annotated[Optional[str], Field(title="Deal Id")] = None
    risk_level: Annotated[str, Field(title="Risk Level")]
    status: Annotated[str, Field(title="Status")]
    title: Annotated[Optional[str], Field(title="Title")] = None


class AgentRunStatus(Enum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"
    cancelled = "cancelled"


class AliasCreate(BaseModel):
    alias: Annotated[str, Field(max_length=255, min_length=1, title="Alias")]
    alias_type: Annotated[Optional[str], Field(max_length=50, title="Alias Type")] = (
        "general"
    )


class AuthUrlResponse(BaseModel):
    auth_url: Annotated[str, Field(title="Auth Url")]
    state: Annotated[str, Field(title="State")]


class DisplayName(RootModel[str]):
    root: Annotated[str, Field(max_length=255, title="Display Name")]


class FolderPath(RootModel[str]):
    root: Annotated[str, Field(max_length=1024, title="Folder Path")]


class Stage(Enum):
    inbound = "inbound"
    screening = "screening"
    qualified = "qualified"
    loi = "loi"
    diligence = "diligence"
    closing = "closing"
    portfolio = "portfolio"
    junk = "junk"
    archived = "archived"


class DealCreate(BaseModel):
    broker: Annotated[Optional[Dict[str, Any]], Field(title="Broker")] = None
    canonical_name: Annotated[str, Field(max_length=255, title="Canonical Name")]
    company_info: Annotated[Optional[Dict[str, Any]], Field(title="Company Info")] = (
        None
    )
    display_name: Annotated[Optional[DisplayName], Field(title="Display Name")] = None
    folder_path: Annotated[Optional[FolderPath], Field(title="Folder Path")] = None
    identifiers: Annotated[Optional[Dict[str, Any]], Field(title="Identifiers")] = None
    metadata: Annotated[Optional[Dict[str, Any]], Field(title="Metadata")] = None
    stage: Annotated[Optional[Stage], Field(title="Stage")] = "inbound"
    status: Annotated[Optional[str], Field(title="Status")] = "active"


class DealEvent(BaseModel):
    actor: Annotated[Optional[str], Field(title="Actor")] = None
    created_at: Annotated[datetime, Field(title="Created At")]
    deal_id: Annotated[str, Field(title="Deal Id")]
    details: Annotated[Optional[Dict[str, Any]], Field(title="Details")] = None
    event_type: Annotated[str, Field(title="Event Type")]
    id: Annotated[UUID, Field(title="Id")]
    source: Annotated[Optional[str], Field(title="Source")] = None


class DealResponse(BaseModel):
    action_count: Annotated[Optional[int], Field(title="Action Count")] = None
    alias_count: Annotated[Optional[int], Field(title="Alias Count")] = None
    broker: Annotated[Dict[str, Any], Field(title="Broker")]
    canonical_name: Annotated[str, Field(title="Canonical Name")]
    company_info: Annotated[Dict[str, Any], Field(title="Company Info")]
    created_at: Annotated[datetime, Field(title="Created At")]
    days_since_update: Annotated[Optional[float], Field(title="Days Since Update")] = (
        None
    )
    deal_id: Annotated[str, Field(title="Deal Id")]
    display_name: Annotated[Optional[str], Field(title="Display Name")] = None
    folder_path: Annotated[Optional[str], Field(title="Folder Path")] = None
    identifiers: Annotated[Dict[str, Any], Field(title="Identifiers")]
    metadata: Annotated[Dict[str, Any], Field(title="Metadata")]
    stage: Annotated[str, Field(title="Stage")]
    status: Annotated[str, Field(title="Status")]
    updated_at: Annotated[datetime, Field(title="Updated At")]


class DealSearchResult(BaseModel):
    canonical_name: Annotated[str, Field(title="Canonical Name")]
    company_name: Annotated[Optional[str], Field(title="Company Name")] = None
    created_at: Annotated[str, Field(title="Created At")]
    deal_id: Annotated[str, Field(title="Deal Id")]
    stage: Annotated[str, Field(title="Stage")]
    status: Annotated[str, Field(title="Status")]
    updated_at: Annotated[Optional[str], Field(title="Updated At")] = None


class CanonicalName(RootModel[str]):
    root: Annotated[str, Field(max_length=255, title="Canonical Name")]


class DealUpdate(BaseModel):
    broker: Annotated[Optional[Dict[str, Any]], Field(title="Broker")] = None
    canonical_name: Annotated[
        Optional[CanonicalName], Field(title="Canonical Name")
    ] = None
    company_info: Annotated[Optional[Dict[str, Any]], Field(title="Company Info")] = (
        None
    )
    display_name: Annotated[Optional[DisplayName], Field(title="Display Name")] = None
    folder_path: Annotated[Optional[FolderPath], Field(title="Folder Path")] = None
    identifiers: Annotated[Optional[Dict[str, Any]], Field(title="Identifiers")] = None
    metadata: Annotated[Optional[Dict[str, Any]], Field(title="Metadata")] = None
    stage: Annotated[Optional[Stage], Field(title="Stage")] = None
    status: Annotated[Optional[str], Field(title="Status")] = None


class EmailAccountResponse(BaseModel):
    created_at: Annotated[Optional[datetime], Field(title="Created At")] = None
    email_address: Annotated[str, Field(title="Email Address")]
    id: Annotated[str, Field(title="Id")]
    is_active: Annotated[bool, Field(title="Is Active")]
    provider: Annotated[str, Field(title="Provider")]


class EmailMessageResponse(BaseModel):
    body_preview: Annotated[str, Field(title="Body Preview")]
    cc_addresses: Annotated[List[str], Field(title="Cc Addresses")]
    from_address: Annotated[str, Field(title="From Address")]
    has_attachments: Annotated[bool, Field(title="Has Attachments")]
    id: Annotated[str, Field(title="Id")]
    is_outbound: Annotated[bool, Field(title="Is Outbound")]
    sent_at: Annotated[datetime, Field(title="Sent At")]
    subject: Annotated[str, Field(title="Subject")]
    thread_id: Annotated[str, Field(title="Thread Id")]
    to_addresses: Annotated[List[str], Field(title="To Addresses")]


class EmailThreadResponse(BaseModel):
    deal_id: Annotated[Optional[str], Field(title="Deal Id")] = None
    id: Annotated[str, Field(title="Id")]
    last_message_at: Annotated[datetime, Field(title="Last Message At")]
    message_count: Annotated[int, Field(title="Message Count")]
    participants: Annotated[List[str], Field(title="Participants")]
    provider: Annotated[Optional[str], Field(title="Provider")] = None
    subject: Annotated[str, Field(title="Subject")]
    thread_id: Annotated[str, Field(title="Thread Id")]


class Detail(BaseModel):
    code: Annotated[Optional[str], Field(description="Error code for this field")] = (
        None
    )
    field: Annotated[
        Optional[str], Field(description="Field path that caused the error")
    ] = None
    message: Annotated[
        Optional[str], Field(description="Error message for this field")
    ] = None


class Error(BaseModel):
    code: Annotated[
        str, Field(description="Machine-readable error code", examples=["NOT_FOUND"])
    ]
    details: Annotated[
        Optional[List[Detail]],
        Field(description="Additional error details for validation errors"),
    ] = None
    message: Annotated[
        str,
        Field(
            description="Human-readable error message", examples=["Resource not found"]
        ),
    ]
    timestamp: Annotated[
        Optional[datetime], Field(description="When the error occurred")
    ] = None
    trace_id: Annotated[
        Optional[str], Field(description="Unique trace ID for debugging")
    ] = None


class EventResponse(BaseModel):
    correlation_id: Annotated[Optional[str], Field(title="Correlation Id")] = None
    data: Annotated[Dict[str, Any], Field(title="Data")]
    id: Annotated[str, Field(title="Id")]
    timestamp: Annotated[str, Field(title="Timestamp")]
    type: Annotated[str, Field(title="Type")]


class EventsListResponse(BaseModel):
    count: Annotated[int, Field(title="Count")]
    events: Annotated[List[EventResponse], Field(title="Events")]


class InboxResponse(BaseModel):
    count: Annotated[int, Field(title="Count")]
    messages: Annotated[List[EmailMessageResponse], Field(title="Messages")]


class InvokeRequest(BaseModel):
    context: Annotated[Optional[Dict[str, Any]], Field(title="Context")] = None
    deal_id: Annotated[UUID, Field(title="Deal Id")]
    task: Annotated[str, Field(title="Task")]


class LangSmithInvokeRequest(BaseModel):
    context: Annotated[
        Optional[Dict[str, Any]],
        Field(description="Context for the task", title="Context"),
    ] = None
    stream: Annotated[
        Optional[bool],
        Field(description="Whether to stream the response", title="Stream"),
    ] = False
    task: Annotated[
        str, Field(description="The task for the agent to perform", title="Task")
    ]
    task_type: Annotated[
        Optional[str],
        Field(description="Type of task for model selection", title="Task Type"),
    ] = "tool_orchestration"


class LangSmithInvokeResponse(BaseModel):
    duration_ms: Annotated[Optional[float], Field(title="Duration Ms")] = None
    error: Annotated[Optional[str], Field(title="Error")] = None
    fallback_reason: Annotated[Optional[str], Field(title="Fallback Reason")] = None
    is_fallback: Annotated[Optional[bool], Field(title="Is Fallback")] = False
    model_used: Annotated[str, Field(title="Model Used")]
    response: Annotated[Optional[str], Field(title="Response")] = None
    success: Annotated[bool, Field(title="Success")]
    tool_calls: Annotated[Optional[List[Dict[str, Any]]], Field(title="Tool Calls")] = (
        []
    )
    tool_results: Annotated[
        Optional[List[Dict[str, Any]]], Field(title="Tool Results")
    ] = []
    trace_id: Annotated[str, Field(title="Trace Id")]


class LinkThreadBody(BaseModel):
    deal_id: Annotated[str, Field(title="Deal Id")]
    provider: Annotated[Optional[str], Field(title="Provider")] = "gmail"
    thread_id: Annotated[str, Field(title="Thread Id")]


class Meta(BaseModel):
    has_more: Annotated[bool, Field(description="Whether more items exist")]
    limit: Annotated[int, Field(description="Maximum items per page")]
    offset: Annotated[int, Field(description="Current offset")]
    timestamp: Optional[datetime] = None
    total: Annotated[int, Field(description="Total number of items")]
    trace_id: Annotated[str, Field(description="Unique trace ID")]


class ListResponse(BaseModel):
    data: Annotated[Optional[List], Field(description="List of items")] = None
    meta: Optional[Meta] = None


class LoginRequest(BaseModel):
    email: Annotated[EmailStr, Field(title="Email")]
    password: Annotated[str, Field(title="Password")]


class LogoutResponse(BaseModel):
    message: Annotated[str, Field(title="Message")]


class NoteCreate(BaseModel):
    category: Annotated[Optional[str], Field(max_length=50, title="Category")] = (
        "general"
    )
    content: Annotated[str, Field(max_length=10000, min_length=1, title="Content")]


class OAuthCallbackResponse(BaseModel):
    email: Annotated[Optional[str], Field(title="Email")] = None
    message: Annotated[str, Field(title="Message")]
    success: Annotated[bool, Field(title="Success")]


class OperatorResponse(BaseModel):
    email: Annotated[str, Field(title="Email")]
    id: Annotated[str, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    role: Annotated[str, Field(title="Role")]


class Pagination(BaseModel):
    page: Optional[int] = None
    per_page: Optional[int] = None
    total: Optional[int] = None
    total_pages: Optional[int] = None


class PipelineSummary(BaseModel):
    avg_days_in_stage: Annotated[Optional[float], Field(title="Avg Days In Stage")] = (
        None
    )
    count: Annotated[int, Field(title="Count")]
    stage: Annotated[str, Field(title="Stage")]


class Action(Enum):
    approve = "approve"
    reject = "reject"


class ProposalExecuteRequest(BaseModel):
    action: Annotated[Optional[Action], Field(title="Action")] = "approve"
    approved_by: Annotated[str, Field(title="Approved By")]
    proposal_id: Annotated[str, Field(title="Proposal Id")]
    reject_reason: Annotated[Optional[str], Field(title="Reject Reason")] = None
    session_id: Annotated[str, Field(title="Session Id")]


class PurgeRequest(BaseModel):
    days: Annotated[Optional[int], Field(title="Days")] = 30
    reason: Annotated[Optional[str], Field(title="Reason")] = None


class QuarantineCreate(BaseModel):
    broker_name: Annotated[Optional[str], Field(title="Broker Name")] = None
    classification: Annotated[Optional[str], Field(title="Classification")] = "unknown"
    company_name: Annotated[Optional[str], Field(title="Company Name")] = None
    confidence: Annotated[Optional[float], Field(title="Confidence")] = None
    email_subject: Annotated[Optional[str], Field(title="Email Subject")] = None
    is_broker: Annotated[Optional[bool], Field(title="Is Broker")] = None
    message_id: Annotated[str, Field(title="Message Id")]
    raw_body: Annotated[Optional[str], Field(title="Raw Body")] = None
    received_at: Annotated[Optional[datetime], Field(title="Received At")] = None
    sender: Annotated[Optional[str], Field(title="Sender")] = None
    sender_company: Annotated[Optional[str], Field(title="Sender Company")] = None
    sender_domain: Annotated[Optional[str], Field(title="Sender Domain")] = None
    sender_name: Annotated[Optional[str], Field(title="Sender Name")] = None
    urgency: Annotated[Optional[str], Field(title="Urgency")] = "normal"


class QuarantineProcess(BaseModel):
    action: Annotated[str, Field(pattern="^(approve|reject)$", title="Action")]
    deal_id: Annotated[Optional[str], Field(title="Deal Id")] = None
    notes: Annotated[Optional[str], Field(title="Notes")] = None
    processed_by: Annotated[Optional[str], Field(title="Processed By")] = "ui_user"


class QuarantineResponse(BaseModel):
    broker_name: Annotated[Optional[str], Field(title="Broker Name")] = None
    classification: Annotated[str, Field(title="Classification")]
    company_name: Annotated[Optional[str], Field(title="Company Name")] = None
    confidence: Annotated[Optional[float], Field(title="Confidence")] = None
    created_at: Annotated[datetime, Field(title="Created At")]
    email_subject: Annotated[Optional[str], Field(title="Email Subject")] = None
    id: Annotated[str, Field(title="Id")]
    is_broker: Annotated[Optional[bool], Field(title="Is Broker")] = None
    message_id: Annotated[Optional[str], Field(title="Message Id")] = None
    received_at: Annotated[Optional[datetime], Field(title="Received At")] = None
    sender: Annotated[Optional[str], Field(title="Sender")] = None
    sender_company: Annotated[Optional[str], Field(title="Sender Company")] = None
    sender_domain: Annotated[Optional[str], Field(title="Sender Domain")] = None
    sender_name: Annotated[Optional[str], Field(title="Sender Name")] = None
    status: Annotated[str, Field(title="Status")]
    urgency: Annotated[str, Field(title="Urgency")]


class RegisterRequest(BaseModel):
    email: Annotated[EmailStr, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    password: Annotated[str, Field(title="Password")]


class ResponseMeta(BaseModel):
    correlation_id: Annotated[
        Optional[str], Field(description="Correlation ID for related requests")
    ] = None
    timestamp: Annotated[datetime, Field(description="Response timestamp")]
    trace_id: Annotated[UUID, Field(description="Unique trace ID for this request")]


class RetryRequest(BaseModel):
    reason: Annotated[Optional[str], Field(title="Reason")] = None


class SSEStatsResponse(BaseModel):
    active_connections: Annotated[int, Field(title="Active Connections")]
    replay_buffer_size: Annotated[int, Field(title="Replay Buffer Size")]
    total_sequence: Annotated[Optional[int], Field(title="Total Sequence")] = None


class SearchEmailBody(BaseModel):
    after: Annotated[Optional[datetime], Field(title="After")] = None
    before: Annotated[Optional[datetime], Field(title="Before")] = None
    from_address: Annotated[Optional[str], Field(title="From Address")] = None
    has_attachment: Annotated[Optional[bool], Field(title="Has Attachment")] = None
    max_results: Annotated[Optional[int], Field(le=100, title="Max Results")] = 20
    query: Annotated[Optional[str], Field(title="Query")] = None
    subject: Annotated[Optional[str], Field(title="Subject")] = None
    to_address: Annotated[Optional[str], Field(title="To Address")] = None


class SendEmailBody(BaseModel):
    bcc: Annotated[Optional[List[str]], Field(title="Bcc")] = None
    body: Annotated[str, Field(title="Body")]
    cc: Annotated[Optional[List[str]], Field(title="Cc")] = None
    deal_id: Annotated[Optional[str], Field(title="Deal Id")] = None
    is_html: Annotated[Optional[bool], Field(title="Is Html")] = False
    reply_to_thread_id: Annotated[Optional[str], Field(title="Reply To Thread Id")] = (
        None
    )
    subject: Annotated[str, Field(min_length=1, title="Subject")]
    to: Annotated[List[str], Field(min_length=1, title="To")]


class SendEmailResponse(BaseModel):
    message_id: Annotated[str, Field(title="Message Id")]
    success: Annotated[bool, Field(title="Success")]
    thread_id: Annotated[str, Field(title="Thread Id")]


class SuccessResponse(BaseModel):
    data: Annotated[
        Optional[Any], Field(description="Response data (type varies by endpoint)")
    ] = None
    meta: Optional[ResponseMeta] = None


class ToolCall(BaseModel):
    id: Annotated[Optional[UUID], Field(title="Id")] = None
    timestamp: Annotated[Optional[datetime], Field(title="Timestamp")] = None
    tool_input: Annotated[Dict[str, Any], Field(title="Tool Input")]
    tool_name: Annotated[str, Field(title="Tool Name")]


class ToolSchema(BaseModel):
    description: Annotated[str, Field(title="Description")]
    name: Annotated[str, Field(title="Name")]
    parameters: Annotated[Dict[str, Any], Field(title="Parameters")]
    requires_approval: Annotated[bool, Field(title="Requires Approval")]
    risk_level: Annotated[str, Field(title="Risk Level")]


class IdempotencyKey(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Unique key for safe retries. Same key within 24h returns cached result.",
            max_length=64,
            title="Idempotency Key",
        ),
    ]


class TransitionRequest(BaseModel):
    idempotency_key: Annotated[
        Optional[IdempotencyKey],
        Field(
            description="Unique key for safe retries. Same key within 24h returns cached result.",
            title="Idempotency Key",
        ),
    ] = None
    new_stage: Annotated[str, Field(title="New Stage")]
    reason: Annotated[Optional[str], Field(title="Reason")] = None


class TransitionResponse(BaseModel):
    deal_id: Annotated[str, Field(title="Deal Id")]
    from_stage: Annotated[str, Field(title="From Stage")]
    idempotent_hit: Annotated[Optional[bool], Field(title="Idempotent Hit")] = False
    success: Annotated[bool, Field(title="Success")]
    timestamp: Annotated[str, Field(title="Timestamp")]
    to_stage: Annotated[str, Field(title="To Stage")]


class ValidTransitionsResponse(BaseModel):
    current_stage: Annotated[Optional[str], Field(title="Current Stage")] = None
    deal_id: Annotated[str, Field(title="Deal Id")]
    valid_transitions: Annotated[List[str], Field(title="Valid Transitions")]


class ValidationError(BaseModel):
    ctx: Annotated[Optional[Dict[str, Any]], Field(title="Context")] = None
    input: Annotated[Optional[Any], Field(title="Input")] = None
    loc: Annotated[List[Union[str, int]], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class ActionSearchResponse(BaseModel):
    has_more: Annotated[Optional[bool], Field(title="Has More")] = False
    limit: Annotated[int, Field(title="Limit")]
    next_cursor: Annotated[Optional[str], Field(title="Next Cursor")] = None
    query: Annotated[str, Field(title="Query")]
    results: Annotated[List[ActionSearchResult], Field(title="Results")]


class AgentRunResponse(BaseModel):
    actions_created: Annotated[Optional[List[UUID]], Field(title="Actions Created")] = (
        []
    )
    completed_at: Annotated[Optional[datetime], Field(title="Completed At")] = None
    deal_id: Annotated[UUID, Field(title="Deal Id")]
    error: Annotated[Optional[str], Field(title="Error")] = None
    result: Annotated[Optional[Dict[str, Any]], Field(title="Result")] = None
    run_id: Annotated[UUID, Field(title="Run Id")]
    started_at: Annotated[datetime, Field(title="Started At")]
    status: AgentRunStatus
    tool_calls: Annotated[Optional[List[ToolCall]], Field(title="Tool Calls")] = []
    trace_id: Annotated[str, Field(title="Trace Id")]


class DealSearchResponse(BaseModel):
    has_more: Annotated[Optional[bool], Field(title="Has More")] = False
    limit: Annotated[int, Field(title="Limit")]
    next_cursor: Annotated[Optional[str], Field(title="Next Cursor")] = None
    offset: Annotated[Optional[int], Field(title="Offset")] = None
    query: Annotated[str, Field(title="Query")]
    results: Annotated[List[DealSearchResult], Field(title="Results")]
    total: Annotated[Optional[int], Field(title="Total")] = None


class DealThreadsResponse(BaseModel):
    count: Annotated[int, Field(title="Count")]
    threads: Annotated[List[EmailThreadResponse], Field(title="Threads")]


class ErrorResponse(BaseModel):
    error: Optional[Error] = None
    meta: Optional[ResponseMeta] = None


class HTTPValidationError(BaseModel):
    detail: Annotated[Optional[List[ValidationError]], Field(title="Detail")] = None


class LoginResponse(BaseModel):
    message: Annotated[str, Field(title="Message")]
    operator: OperatorResponse


class PaginatedResponse(BaseModel):
    data: Optional[List[Dict[str, Any]]] = None
    meta: Optional[ResponseMeta] = None
    pagination: Optional[Pagination] = None
