# generated by datamodel-codegen:
#   filename:  rag-api.json
#   timestamp: 2026-02-06T20:42:54+00:00

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


class AddContentRequest(BaseModel):
    chunk_size: Annotated[Optional[int], Field(title="Chunk Size")] = 5000
    content: Annotated[str, Field(title="Content")]
    metadata: Annotated[Optional[Dict[str, Any]], Field(title="Metadata")] = None
    url: Annotated[str, Field(title="Url")]


class QueryRequest(BaseModel):
    match_count: Annotated[Optional[int], Field(title="Match Count")] = 5
    query: Annotated[str, Field(title="Query")]
    source: Annotated[Optional[str], Field(title="Source")] = None


class ValidationError(BaseModel):
    loc: Annotated[List[Union[str, int]], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class HTTPValidationError(BaseModel):
    detail: Annotated[Optional[List[ValidationError]], Field(title="Detail")] = None
